"""Runtime app.js wording; inject wording(language) as #app-wording JSON.

Narrative errors and pipeline wording remain separate server dictionaries.
Unsupported languages fall back to Korean. Each call returns a fresh flat dict.
"""

APP_WORDING: dict[str, dict[str, str]] = {
    "ko": {
        "menu.close": "메뉴 접기",
        "menu.open": "메뉴 펼치기",
        "form.error": ("작업을 완료하지 못했습니다. 기술 정보에서 원인을 확인하세요."),
        "form.deny": (
            "이 배포를 거절할까요? 이 실행은 여기서 끝나고 서비스는 지금 버전을 유지합니다."
        ),
        "form.request_failed": ("요청을 처리하지 못했습니다. 다시 시도해 주세요."),
        "check.needed": "확인 필요",
        "check.docker_failed": "Docker Hub 연결 확인 실패",
        "refresh.disconnected": (
            "자동 갱신 연결이 끊겼습니다. 표시된 기록을 유지하며 다시 확인합니다."
        ),
        "run.running": "배포 중",
        "run.approved": "승인됨 · 곧 시작",
        "run.succeeded": "배포 완료",
        "run.failed_local": "온프레미스 배포 실패",
        "run.failed_cloud": "클라우드 배포 실패",
        "run.failed_verify": "배포 후 검증 실패",
        "run.failed_before_deploy": "배포 전에 중단",
        "run.parity_failed": "두 환경 결과가 다름",
        "run.needs_human": "직접 확인 필요",
        "run.cancelled": "취소됨",
        "run.superseded": "새 승인 자료로 대체됨",
        "state.running": "진행 중",
        "state.waiting": "대기",
        "state.succeeded": "완료",
        "state.failed": "실패",
        "state.check_failed": "검사 불합격",
        "state.skipped": "건너뜀",
        "state.unrecorded": "기록 없음",
        "event.state": "상태",
        "event.started": "시작",
        "event.gate_waiting": "앞 단계 대기",
        "event.gate_opened": "앞 단계 완료",
        "event.gate_failed": "앞 단계 실패",
        "event.rollback_started": "복구 시작",
        "event.rollback_finished": "복구 완료",
        "event.stage_finished": "준비 단계 기록",
        "event.report_ready": "보고 완료",
        "event.ai_call": "제안 기록",
        "task.name": "실행 작업",
        "task.running": "작업이 진행 중입니다.",
        "task.finished": "작업을 마쳤습니다.",
        "task.failed": "작업을 완료하지 못했습니다.",
        "task.waiting": "앞 단계 완료를 기다립니다.",
        "task.skipped": "이번 실행에서는 건너뛰었습니다.",
        "state.checking": "확인 중",
        "task.check_record": "실행 기록을 확인합니다.",
        "task.start": "작업 시작",
        "time.unrecorded": "시간 기록 없음",
        "time.start_unrecorded": "시작 시각 기록 없음",
        "connection.waiting": "연결 유지 · 완료 기록 대기",
        "connection.reconnecting": "다시 연결하는 중",
        "gate.previous": "앞 단계",
        "gate.failed": ("앞 단계 실패로 대기를 해제했습니다. 이 작업은 실행하지 않습니다."),
        "compare.skipped": "한 환경이 실패해 두 환경을 비교하지 않았습니다.",
        "task.previous_unrecorded": "앞 작업의 실행 기록 없음",
        "state.check_record": "기록 확인",
        "task.unaffected": "이 환경은 영향 없이 계속 진행합니다.",
        "task.candidate_ready": ("실행 단계 시작 · 승인본 소스 준비 완료로 추정합니다."),
        "time.missing": "시각 없음",
        "event.record": "기록",
        "connection.live": "실시간 연결됨 · 이벤트 시각은 KST",
        "task.next_preparing": "다음 작업 준비 중",
        "track.local": "온프레미스",
        "track.cloud": "클라우드",
        "track.common": "공통",
        "task.next_waiting": "다음 실행 상태를 기다립니다.",
        "run.check_state": "실행 상태 확인",
        "task.not_run": "실행 안 함 · 앞 단계 실패로 실행 기록이 없습니다.",
        "task.no_completion": "완료 기록이 없습니다. 결과를 확인하세요.",
        "run.ended": "실행 종료",
        "run.result": ("실행이 끝났습니다. 환경별 최종 상태는 결과 화면에서 확인하세요."),
        "run.final_received": "최종 상태를 받았습니다.",
        "connection.lost": (
            "실시간 연결이 끊겼습니다. 배포 중단 여부는 "
            "아직 확인되지 않았으며 자동으로 다시 연결합니"
            "다."
        ),
        "selection.count": "{total}개 중 {selected}개 선택",
        "time.minutes": "{minutes}분 {seconds}초",
        "time.seconds": "{seconds}초",
        "refresh.checked": "최신 상태 확인 · {time}",
        "time.running": "진행 {elapsed}",
        "time.lane": "환경 시작 후 {elapsed}",
        "steps.remaining": "남은 단계 {count}개{estimate}",
        "steps.estimate": " · 이전 성공 기준 약 {elapsed}",
        "steps.processed": "{done}/{total} 작업 처리",
        "event.age": "마지막 이벤트 {elapsed} 전 · {connection}",
        "gate.waiting": "{gate} 완료를 기다립니다.",
        "locale": "ko-KR",
    },
    "ja": {
        "menu.close": "メニューを閉じる",
        "menu.open": "メニューを開く",
        "form.error": ("処理を完了できませんでした。技術情報で原因を確認してください。"),
        "form.deny": (
            "このデプロイを拒否しますか?この実行はここで終了し"
            "、サービスは現在のバージョンを維持します。"
        ),
        "form.request_failed": ("リクエストを処理できませんでした。もう一度お試しください。"),
        "check.needed": "確認が必要",
        "check.docker_failed": "Docker Hubの接続確認に失敗",
        "refresh.disconnected": (
            "自動更新の接続が切れました。表示中の記録を維持して再確認します。"
        ),
        "run.running": "デプロイ中",
        "run.approved": "承認済み · まもなく開始",
        "run.succeeded": "デプロイ完了",
        "run.failed_local": "オンプレミスのデプロイに失敗",
        "run.failed_cloud": "クラウドのデプロイに失敗",
        "run.failed_verify": "デプロイ後の検証に失敗",
        "run.failed_before_deploy": "デプロイ前に停止",
        "run.parity_failed": "両環境の結果が異なります",
        "run.needs_human": "手動での確認が必要",
        "run.cancelled": "キャンセル済み",
        "run.superseded": "新しい承認資料に置き換え済み",
        "state.running": "実行中",
        "state.waiting": "待機",
        "state.succeeded": "完了",
        "state.failed": "失敗",
        "state.check_failed": "検査不合格",
        "state.skipped": "スキップ",
        "state.unrecorded": "記録なし",
        "event.state": "状態",
        "event.started": "開始",
        "event.gate_waiting": "前のステップを待機",
        "event.gate_opened": "前のステップが完了",
        "event.gate_failed": "前のステップが失敗",
        "event.rollback_started": "復旧開始",
        "event.rollback_finished": "復旧完了",
        "event.stage_finished": "準備ステップの記録",
        "event.report_ready": "レポート完了",
        "event.ai_call": "提案の記録",
        "task.name": "実行タスク",
        "task.running": "タスクを実行中です。",
        "task.finished": "タスクが完了しました。",
        "task.failed": "タスクを完了できませんでした。",
        "task.waiting": "前のステップの完了を待っています。",
        "task.skipped": "今回の実行ではスキップしました。",
        "state.checking": "確認中",
        "task.check_record": "実行記録を確認します。",
        "task.start": "タスク開始",
        "time.unrecorded": "時間の記録なし",
        "time.start_unrecorded": "開始時刻の記録なし",
        "connection.waiting": "接続維持 · 完了記録を待機",
        "connection.reconnecting": "再接続中",
        "gate.previous": "前のステップ",
        "gate.failed": ("前のステップの失敗により待機を解除しました。このタスクは実行しません。"),
        "compare.skipped": ("一方の環境が失敗したため、両環境の比較は行いませんでした。"),
        "task.previous_unrecorded": "前のタスクの実行記録なし",
        "state.check_record": "記録確認",
        "task.unaffected": "この環境は影響を受けずに実行を続けます。",
        "task.candidate_ready": ("実行ステップ開始 · 承認済みソースの準備が完了したと推定します。"),
        "time.missing": "時刻なし",
        "event.record": "記録",
        "connection.live": "リアルタイム接続中 · イベント時刻はKST",
        "task.next_preparing": "次のタスクを準備中",
        "track.local": "オンプレミス",
        "track.cloud": "クラウド",
        "track.common": "共通",
        "task.next_waiting": "次の実行状態を待っています。",
        "run.check_state": "実行状態を確認",
        "task.not_run": ("未実行 · 前のステップが失敗したため実行記録がありません。"),
        "task.no_completion": ("完了記録がありません。結果を確認してください。"),
        "run.ended": "実行終了",
        "run.result": ("実行が終了しました。各環境の最終状態は結果画面で確認してください。"),
        "run.final_received": "最終状態を受信しました。",
        "connection.lost": (
            "リアルタイム接続が切れました。デプロイが停止したか"
            "はまだ確認できていません。自動で再接続します。"
        ),
        "selection.count": "{total}件中{selected}件を選択",
        "time.minutes": "{minutes}分{seconds}秒",
        "time.seconds": "{seconds}秒",
        "refresh.checked": "最新の状態を確認 · {time}",
        "time.running": "経過 {elapsed}",
        "time.lane": "環境の開始から {elapsed}",
        "steps.remaining": "残り{count}ステップ{estimate}",
        "steps.estimate": " · 前回の成功時を基準に約{elapsed}",
        "steps.processed": "{done}/{total}タスク処理済み",
        "event.age": "最終イベントは{elapsed}前 · {connection}",
        "gate.waiting": "{gate}の完了を待っています。",
        "locale": "ja-JP",
    },
}


def wording(language: str) -> dict[str, str]:
    """Return KO/JA strings (also accepts ko-KR and ja-JP)."""
    key = language.lower().replace("_", "-").split("-", 1)[0]
    return APP_WORDING.get(key, APP_WORDING["ko"]).copy()
